# Generated by Django 5.2.4 on 2025-08-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя художника')),
                ('bio', models.TextField(blank=True, verbose_name='Короткая информация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artist/', verbose_name='Фото художника')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художник',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-имя')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Обложка поста')),
            ],
            options={
                'verbose_name': 'Пост в блоге',
                'verbose_name_plural': 'Посты в блоге',
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на обратную связь',
                'verbose_name_plural': 'Заявки на обратную связь',
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранная')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-имя')),
                ('image', models.ImageField(upload_to='paintings/original/', verbose_name='Оригинальное изображение')),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='paintings/small/', verbose_name='Маленькое изображение (для каталога)')),
                ('medium_image', models.ImageField(blank=True, null=True, upload_to='paintings/medium/', verbose_name='Среднее изображение (для избранного)')),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='paintings/large/', verbose_name='Большое изображение (для страницы)')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
            },
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('vk_link', models.URLField(blank=True, help_text='Полная ссылка, например: https://vk.com/username', verbose_name='Ссылка на VK')),
                ('instagram_link', models.URLField(blank=True, help_text='Полная ссылка, например: https://instagram.com/username', verbose_name='Ссылка на Instagram*')),
                ('telegram_link', models.URLField(blank=True, help_text='Полная ссылка, например: https://t.me/username', verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.blogpost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Изображение поста',
                'verbose_name_plural': 'Изображения постов',
            },
        ),
    ]
