# Generated by Django 5.2.4 on 2025-08-07 01:32

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию художника (будет обработана автоматически).', null=True, storage=core.storage.OverwriteStorage(), upload_to='artist/', verbose_name='Фото художника'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение обложки (будет обработано автоматически).', null=True, storage=core.storage.OverwriteStorage(), upload_to='blog/covers/', verbose_name='Обложка поста'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для поста (будет обработано автоматически).', null=True, storage=core.storage.OverwriteStorage(), upload_to='blog/images/', verbose_name='Изображение'),
        ),
    ]
